<?php

namespace App\Helpers;

use Awcodes\Curator\Models\Media;

trait HasMedia
{
//    public function __get($key)
//    {
//        if (in_array($key.'_id', $this->upload_attributes)) {
//            $key = $key . '_id';
//            dd(Media::where('id', $this->translate(app()->getLocale())->$key)->first()->toArray());
//        }
//        return parent::__get($key); // TODO: Change the autogenerated stub
//    }

//    public function image(){
//        return $this->hasOne(Media::class, 'id', 'image_id');
//    }
}