<?php

namespace App\Exceptions;

use App\Http\Controllers\SiteController;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    function render($request, Throwable $e)
    {
        if ($e instanceof ModelNotFoundException){
            if ($request->route()->getName() == "news.show"){
                return redirect()->route('news.index');
            }
        }

        if ($this->isHttpException($e)){
            if ($e->getStatusCode() == 404){
                return response()->view('errors.404', [
                    'language' => app()->getLocale(),
                ]);
            }
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
